from selenium.webdriver.common.by import By


class Locators:
    category_georgia = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[1]/a[1]')
    category_main_dishes = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[1]/a[2]')
    category_breakfast = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[1]/a[3]')
    category_pizza = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[1]/a[4]')
    category_pies = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[1]/a[5]')
    category_sets_sushi_rolls = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[1]')
    category_onigiri = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[2]')
    category_combo_sets = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[3]')
    category_burgers = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[4]')
    category_streetfood = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[5]')
    category_snacks = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[6]')
    category_bowls = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[7]')
    category_woks = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[8]')
    category_salads = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[9]')
    category_soups = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[10]')
    category_desserts = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[11]')
    category_drinks = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[12]')
    category_sauces = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[13]')

    compilations_new = (By.CLASS_NAME, 'new-custom__nav')
    compilations_fastfood = (By.CLASS_NAME, 'fastfood-custom__nav')
    compilations_pan_asian = (By.CLASS_NAME, 'pan-asian-custom__nav')
    compilations_lunch = (By.CLASS_NAME, 'lunch-custom__nav')
    compilations_hearty = (By.CLASS_NAME, 'hearty-custom__nav')
    compilations_light = (By.CLASS_NAME, 'light-custom__nav')
    compilations_shrimps = (By.CLASS_NAME, 'shrimps-custom__nav')
    compilations_salmon = (By.CLASS_NAME, 'salmon-custom__nav')
    compilations_vegetarian_menu = (By.CLASS_NAME, 'vegetarian-menu-custom__nav')
    compilations_for_kids = (By.CLASS_NAME, 'for-kids-custom__nav')
    compilations_sweet = (By.CLASS_NAME, 'sweet-custom__nav')

    footer_navigation_menu_mexican = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[1]/ul/li[1]/a')
    footer_navigation_menu_italian = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[1]/ul/li[2]/a')
    footer_navigation_menu_chinese = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[1]/ul/li[3]/a')
    footer_navigation_menu_japanese = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[1]/ul/li[4]/a')

    footer_navigation_link_our_kitchen = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[1]/a')
    footer_navigation_link_shipping = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[2]/a')
    footer_navigation_link_payment = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[3]/a')
    footer_navigation_link_reviews = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[4]/a')
    footer_navigation_link_contacts = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[5]/a')
    footer_navigation_link_job = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[6]/a')
    footer_navigation_link_franchise = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[7]/a')
    footer_navigation_link_google_form = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[8]/a')

    footer_navigation_app_itunes = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[2]/div[1]/a[1]')
    footer_navigation_app_google_play = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[2]/div[1]/a[2]')
    footer_navigation_app_huawei = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[2]/div[1]/a[3]')

    footer_navigation_soc_vk = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[2]/div[2]/a[1]')
    footer_navigation_soc_telegram = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[2]/div[2]/a[2]')
    footer_navigation_soc_youtube = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[2]/div[2]/a[3]')

    footer_user_agreement = (By.XPATH, '/html/body/div[2]/footer/div[1]/div/ul/li[1]/a')
    footer_license_agreement = (By.XPATH, '/html/body/div[2]/footer/div[1]/div/ul/li[2]/a')
    footer_confidentiality_of_personal_information = (By.XPATH, '/html/body/div[2]/footer/div[1]/div/ul/li[3]/a')
    footer_promo_codes = (By.XPATH, '/html/body/div[2]/footer/div[1]/div/ul/li[4]/a')
    footer_full_menu = (By.XPATH, '/html/body/div[2]/footer/div[1]/div/ul/li[5]/a')
    footer_trademarks = (By.XPATH, '/html/body/div[2]/footer/div[1]/div/ul/li[6]/a')

    promo = (By.XPATH, '/html/body/div[2]/div[3]/aside/nav/div/div/div[4]/div[1]/a')
    promo_present_when_ordering_through_app = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[2]/div[5]/div[3]/a[1]')
    promo_3_for_439 = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[2]/div[5]/div[3]/a[2]')
    promo_2_for_649 = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[2]/div[5]/div[3]/a[3]')
    promo_3_for_1149 = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[2]/div[5]/div[3]/a[4]')
    promo_2_woks_for_499 = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[2]/div[5]/div[3]/a[5]')
    promo_2_for_849 = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[2]/div[5]/div[3]/a[6]')
