from selenium.webdriver.common.by import By


class Locators:
    category_georgia = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[1]/a[1]')
    category_main_dishes = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[1]/a[2]')
    category_breakfast = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[1]/a[3]')
    category_pizza = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[1]/a[4]')
    category_pies = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[1]/a[5]')
    category_sets_sushi_rolls = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[1]')
    category_onigiri = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[2]')
    category_combo_sets = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[3]')
    category_burgers = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[4]')
    category_streetfood = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[5]')
    category_snacks = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[6]')
    category_bowls = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[7]')
    category_woks = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[8]')
    category_salads = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[9]')
    category_soups = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[10]')
    category_desserts = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[11]')
    category_drinks = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[12]')
    category_sauces = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/div[5]/div[2]/a[13]')

    compilations_new = (By.CLASS_NAME, 'new-custom__nav')
    compilations_fastfood = (By.CLASS_NAME, 'fastfood-custom__nav')
    compilations_pan_asian = (By.CLASS_NAME, 'pan-asian-custom__nav')
    compilations_lunch = (By.CLASS_NAME, 'lunch-custom__nav')
    compilations_hearty = (By.CLASS_NAME, 'hearty-custom__nav')
    compilations_light = (By.CLASS_NAME, 'light-custom__nav')
    compilations_shrimps = (By.CLASS_NAME, 'shrimps-custom__nav')
    compilations_salmon = (By.CLASS_NAME, 'salmon-custom__nav')
    compilations_vegetarian_menu = (By.CLASS_NAME, 'vegetarian-menu-custom__nav')
    compilations_for_kids = (By.CLASS_NAME, 'for-kids-custom__nav')
    compilations_sweet = (By.CLASS_NAME, 'sweet-custom__nav')

    footer_navigation_menu_mexican = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[1]/ul/li[1]/a')
    footer_navigation_menu_italian = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[1]/ul/li[2]/a')
    footer_navigation_menu_chinese = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[1]/ul/li[3]/a')
    footer_navigation_menu_japanese = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[1]/ul/li[4]/a')

    footer_navigation_link_our_kitchen = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[1]/a')
    footer_navigation_link_shipping = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[2]/a')
    footer_navigation_link_payment = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[3]/a')
    footer_navigation_link_reviews = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[4]/a')
    footer_navigation_link_contacts = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[5]/a')
    footer_navigation_link_job = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[6]/a')
    footer_navigation_link_franchise = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[7]/a')
    footer_navigation_link_google_form = (By.XPATH, '/html/body/div[2]/div[3]/div/main/div[3]/footer/div/div[1]/div[2]/ul/li[8]/a')